"""Legacy diff format parser for Anthropic Builder responses.

Extracted from anthropic_clients.py lines 2413-2473 and 1300-1354 as part of PR-CLIENT-2.
Handles parsing of legacy git diff format (deprecated but still supported).

This is the deprecated mode where LLM generates raw git diffs.
Kept for backward compatibility only.
"""

import re
import logging
from typing import Optional
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class LegacyDiffParseResult:
    """Result of legacy diff parsing."""

    success: bool
    patch_content: str
    summary: str
    error: Optional[str] = None


class LegacyDiffParser:
    """Parses legacy diff format Builder responses.

    Legacy format uses direct git diff output. This is deprecated
    in favor of structured formats but still supported for compatibility.

    Responsibilities:
    1. Extract diff from response text
    2. Validate diff format
    3. Clean up diff formatting
    """

    def _extract_diff_from_text(self, text: str) -> str:
        """Extract git diff content from text that may contain explanations.

        Extracted from anthropic_clients.py lines 1300-1354.

        Args:
            text: Raw text that may contain diff content

        Returns:
            Extracted diff content or empty string
        """
        lines = text.split("\n")
        diff_lines = []
        in_diff = False

        for line in lines:
            # Start of diff
            if line.startswith("diff --git"):
                in_diff = True
                diff_lines.append(line)
            # Continuation of diff
            elif in_diff:
                # Clean up malformed hunk headers (remove trailing context)
                if line.startswith("@@"):
                    # Extract the valid hunk header part only
                    match = re.match(r"^(@@\s+-\d+,\d+\s+\+\d+,\d+\s+@@)", line)
                    if match:
                        # Use only the valid hunk header, discard anything after
                        clean_line = match.group(1)
                        diff_lines.append(clean_line)
                    else:
                        # Malformed hunk header, skip it
                        logger.warning(f"Skipping malformed hunk header: {line[:80]}")
                        continue
                # Check if still in diff (various diff markers)
                elif (
                    line.startswith(("index ", "---", "+++", "+", "-", " "))
                    or line.startswith("new file mode")
                    or line.startswith("deleted file mode")
                    or line.startswith("similarity index")
                    or line.startswith("rename from")
                    or line.startswith("rename to")
                    or line == ""
                ):
                    diff_lines.append(line)
                # Next diff section
                elif line.startswith("diff --git"):
                    diff_lines.append(line)
                # End of diff (explanatory text or other content)
                else:
                    # Stop if we hit markdown fence or explanatory text
                    if line.startswith("```") or line.startswith("#"):
                        break

        return "\n".join(diff_lines) if diff_lines else ""

    def parse(self, content: str) -> LegacyDiffParseResult:
        """Parse legacy diff format response.

        Extracted from anthropic_clients.py lines 2413-2473.

        Args:
            content: Raw LLM output

        Returns:
            LegacyDiffParseResult with extracted patch or error
        """
        import json

        patch_content = ""
        summary = "Generated by Claude"

        try:
            # Try to parse as direct JSON first
            result_json = json.loads(content)
            patch_content = result_json.get("patch_content", "")
            summary = result_json.get("summary", "Generated by Claude")
        except json.JSONDecodeError:
            # Check if wrapped in markdown code fence
            if "```json" in content:
                # Extract JSON from markdown code block
                json_start = content.find("```json") + 7
                json_end = content.find("```", json_start)
                if json_end > json_start:
                    json_str = content[json_start:json_end].strip()
                    try:
                        result_json = json.loads(json_str)
                        patch_content = result_json.get("patch_content", "")
                        summary = result_json.get("summary", "Generated by Claude")
                    except json.JSONDecodeError:
                        pass

            # If still no patch, try to extract raw diff content
            if not patch_content:
                patch_content = self._extract_diff_from_text(content)
                if not patch_content:
                    # Format validation failed - return error
                    error_msg = "LLM output invalid format - no git diff markers found. Output must start with 'diff --git'"
                    return LegacyDiffParseResult(
                        success=False,
                        patch_content="",
                        summary="",
                        error=error_msg,
                    )

        return LegacyDiffParseResult(
            success=True,
            patch_content=patch_content,
            summary=summary,
        )
