"""Tests for dependency lock file verification."""

import json

# Import from scripts location
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "scripts" / "ci"))

from check_dependency_locks import (
    LockCheckResult,
    check_package_lock_json,
    check_platform_markers,
    check_requirements_dev_txt,
    check_requirements_txt,
)


class TestLockCheckResult:
    """Tests for LockCheckResult dataclass."""

    def test_create_result(self):
        """Can create a result."""
        result = LockCheckResult(
            name="test.txt",
            present=True,
            valid=True,
            up_to_date=True,
            message="OK",
        )
        assert result.name == "test.txt"
        assert result.present is True
        assert result.valid is True


class TestCheckRequirementsTxt:
    """Tests for requirements.txt checking."""

    def test_missing_requirements(self):
        """Reports missing requirements.txt."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = check_requirements_txt(Path(tmpdir))
            assert result.present is False
            assert "not found" in result.message

    def test_missing_pyproject(self):
        """Reports missing pyproject.toml."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "requirements.txt").write_text("# pip-compile\nfoo==1.0")
            result = check_requirements_txt(tmpdir)
            assert result.valid is False
            assert "pyproject.toml" in result.message

    def test_invalid_requirements(self):
        """Reports requirements not from pip-compile."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "requirements.txt").write_text("foo==1.0\n")
            (tmpdir / "pyproject.toml").write_text("[project]\nname = 'test'\n")
            result = check_requirements_txt(tmpdir)
            assert result.valid is False
            assert "pip-compile" in result.message

    def test_valid_requirements(self):
        """Reports valid requirements.txt."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "requirements.txt").write_text(
                "#\n# This file is autogenerated by pip-compile\n#\nfoo==1.0\n"
            )
            (tmpdir / "pyproject.toml").write_text("[project]\nname = 'test'\n")
            result = check_requirements_txt(tmpdir)
            assert result.present is True
            assert result.valid is True


class TestCheckRequirementsDevTxt:
    """Tests for requirements-dev.txt checking."""

    def test_missing_dev_requirements(self):
        """Reports missing requirements-dev.txt."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = check_requirements_dev_txt(Path(tmpdir))
            assert result.present is False

    def test_valid_dev_requirements(self):
        """Reports valid requirements-dev.txt."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "requirements-dev.txt").write_text(
                "#\n# This file is autogenerated by pip-compile\n#\npytest==8.0\n"
            )
            result = check_requirements_dev_txt(tmpdir)
            assert result.present is True
            assert result.valid is True


class TestCheckPackageLockJson:
    """Tests for package-lock.json checking."""

    def test_no_package_json(self):
        """Skips when no package.json."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = check_package_lock_json(Path(tmpdir))
            assert "skipping" in result.message.lower()

    def test_missing_lock(self):
        """Reports missing package-lock.json."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "package.json").write_text('{"name": "test"}')
            result = check_package_lock_json(tmpdir)
            assert result.present is False
            assert "not found" in result.message

    def test_invalid_json(self):
        """Reports invalid JSON."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "package.json").write_text('{"name": "test"}')
            (tmpdir / "package-lock.json").write_text("not json")
            result = check_package_lock_json(tmpdir)
            assert result.valid is False
            assert "Invalid JSON" in result.message

    def test_invalid_structure(self):
        """Reports invalid lock structure."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "package.json").write_text('{"name": "test"}')
            (tmpdir / "package-lock.json").write_text('{"name": "test"}')
            result = check_package_lock_json(tmpdir)
            assert result.valid is False
            assert "Invalid" in result.message

    def test_old_lockfile_version(self):
        """Warns about old lockfile version."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "package.json").write_text('{"name": "test"}')
            (tmpdir / "package-lock.json").write_text(
                json.dumps({"lockfileVersion": 1, "packages": {}})
            )
            result = check_package_lock_json(tmpdir)
            assert result.up_to_date is False
            assert "upgrading" in result.message.lower()

    def test_valid_lock(self):
        """Reports valid package-lock.json."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "package.json").write_text('{"name": "test"}')
            (tmpdir / "package-lock.json").write_text(
                json.dumps({"lockfileVersion": 3, "packages": {}})
            )
            result = check_package_lock_json(tmpdir)
            assert result.present is True
            assert result.valid is True


class TestCheckPlatformMarkers:
    """Tests for platform marker checking."""

    def test_missing_requirements(self):
        """Reports missing requirements.txt."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = check_platform_markers(Path(tmpdir))
            assert result.present is False

    def test_missing_markers(self):
        """Detects missing platform markers."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            # Package present without marker
            (tmpdir / "requirements.txt").write_text(
                "python-magic==0.4.27\npython-magic-bin==0.4.14\n"
            )
            result = check_platform_markers(tmpdir)
            assert result.valid is False
            assert "missing marker" in result.message.lower()

    def test_valid_markers(self):
        """Reports valid platform markers."""
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir = Path(tmpdir)
            (tmpdir / "requirements.txt").write_text(
                'python-magic==0.4.27 ; sys_platform != "win32"\n'
                'python-magic-bin==0.4.14 ; sys_platform == "win32"\n'
                'pywin32==311 ; sys_platform == "win32"\n'
            )
            result = check_platform_markers(tmpdir)
            assert result.valid is True
            assert result.message == "OK"


class TestActualRepoLocks:
    """Tests against actual repository lock files."""

    @pytest.fixture
    def repo_root(self):
        """Get actual repo root."""
        return Path(__file__).parent.parent.parent

    def test_actual_requirements_txt(self, repo_root):
        """Actual requirements.txt is valid."""
        result = check_requirements_txt(repo_root)
        assert result.present is True
        assert result.valid is True

    def test_actual_requirements_dev_txt(self, repo_root):
        """Actual requirements-dev.txt is valid."""
        result = check_requirements_dev_txt(repo_root)
        assert result.present is True
        assert result.valid is True

    def test_actual_package_lock_json(self, repo_root):
        """Actual package-lock.json is valid."""
        result = check_package_lock_json(repo_root)
        assert result.present is True
        assert result.valid is True

    def test_actual_platform_markers(self, repo_root):
        """Actual requirements.txt has platform markers."""
        result = check_platform_markers(repo_root)
        assert result.valid is True
