"""Legacy git diff format parser (DEPRECATED).

This parser handles legacy git diff output from LLM.
This format is deprecated in favor of full-file and structured edit formats.

DEPRECATION WARNING: This parser is maintained for backward compatibility only.
New code should use full_file or structured_edit parsers instead.
"""

import json
import logging
import warnings
from typing import Optional
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class LegacyDiffParseResult:
    """Result of parsing legacy diff output."""

    success: bool
    """Whether parsing succeeded."""

    patch_content: str
    """Extracted git diff patch content."""

    summary: str = "Generated by Claude"
    """Summary description."""

    error: Optional[str] = None
    """Error message if parsing failed."""


class LegacyDiffParser:
    """
    Parser for legacy git diff format (DEPRECATED).

    DEPRECATION WARNING: This format is no longer recommended.
    Use FullFileParser or StructuredEditParser for new implementations.
    """

    def __init__(self):
        """Initialize parser and emit deprecation warning."""
        warnings.warn(
            "LegacyDiffParser is deprecated. Use FullFileParser or StructuredEditParser instead.",
            DeprecationWarning,
            stacklevel=2,
        )

    @staticmethod
    def _extract_diff_from_text(content: str) -> str:
        """
        Extract git diff content from text.

        Looks for 'diff --git' markers and extracts everything from the first
        occurrence to the end, or until common terminating markers.
        """
        if "diff --git" not in content:
            return ""

        # Find the start of the first diff
        start_idx = content.find("diff --git")
        if start_idx == -1:
            return ""

        # Extract from first diff to end (or until terminating markers)
        diff_content = content[start_idx:]

        # Look for common terminating markers that indicate end of diff
        terminators = [
            "\n\n---\n",  # Common markdown separator
            "\n\nNote:",  # Common note section
            "\n\nSummary:",  # Summary section
        ]

        for terminator in terminators:
            term_idx = diff_content.find(terminator)
            if term_idx != -1:
                diff_content = diff_content[:term_idx]

        return diff_content.strip()

    def parse(self, content: str) -> LegacyDiffParseResult:
        """
        Parse legacy git diff output from LLM (DEPRECATED).

        Args:
            content: Raw LLM output

        Returns:
            LegacyDiffParseResult with extracted patch or error
        """
        # Emit deprecation warning on usage
        logger.warning(
            "[LegacyDiffParser] Using deprecated legacy diff format. "
            "Consider migrating to full-file or structured edit formats."
        )

        patch_content = ""
        summary = "Generated by Claude"

        try:
            # Try to parse as direct JSON first
            result_json = json.loads(content)
            patch_content = result_json.get("patch_content", "")
            summary = result_json.get("summary", "Generated by Claude")

        except json.JSONDecodeError:
            # Check if wrapped in markdown code fence
            if "```json" in content:
                # Extract JSON from markdown code block
                json_start = content.find("```json") + 7
                json_end = content.find("```", json_start)
                if json_end > json_start:
                    json_str = content[json_start:json_end].strip()
                    try:
                        result_json = json.loads(json_str)
                        patch_content = result_json.get("patch_content", "")
                        summary = result_json.get("summary", "Generated by Claude")
                    except json.JSONDecodeError:
                        pass

            # If still no patch, try to extract raw diff content
            if not patch_content:
                patch_content = self._extract_diff_from_text(content)

        # Validation
        if not patch_content:
            return LegacyDiffParseResult(
                success=False,
                patch_content="",
                error="LLM output invalid format - no git diff markers found. "
                "Output must start with 'diff --git'",
            )

        return LegacyDiffParseResult(
            success=True,
            patch_content=patch_content,
            summary=summary,
        )
